# Generated by Django 5.2.12 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=255, verbose_name='razao social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome fantasia')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('possui_restricao', models.BooleanField(default=False, verbose_name='possui restricao')),
                ('nota_restricao', models.TextField(blank=True, null=True, verbose_name='nota restricao')),
                ('endereco', models.TextField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('natureza_juridica', models.CharField(blank=True, max_length=100, null=True)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('porte_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('atividade_principal', models.TextField(blank=True, null=True)),
                ('pontuacao_risco', models.IntegerField(blank=True, null=True)),
                ('nivel_risco', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='titulo')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(default='OUTROS', max_length=30)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('url_arquivo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='RASCUNHO', max_length=20)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='AnaliseRiscoFornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pontuacao', models.IntegerField(blank=True, null=True)),
                ('nivel_risco', models.CharField(blank=True, max_length=20, null=True)),
                ('situacao_receita', models.CharField(blank=True, max_length=50, null=True)),
                ('possui_protestos', models.BooleanField(default=False)),
                ('possui_processos', models.BooleanField(default=False)),
                ('noticias_negativas', models.BooleanField(default=False)),
                ('historico_interno', models.TextField(blank=True, null=True)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('relatorio_completo', models.TextField(blank=True, null=True)),
                ('consultado_em', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_risco_fornecedor', to='condominios.condominio')),
                ('consultado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_risco_realizadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_risco', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Analise de Risco',
                'verbose_name_plural': 'Analises de Risco',
                'db_table': 'analises_risco_fornecedor',
            },
        ),
    ]
