# Generated by Django 5.2.12 on 2026-03-28 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade', models.TextField(blank=True, null=True)),
                ('bloco', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pendente_triagem')),
                ('criado_por', models.UUIDField(blank=True, null=True)),
                ('condominio_id', models.UUIDField(blank=True, null=True)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('prioridade', models.TextField(default='media')),
                ('categoria', models.TextField(blank=True, null=True)),
                ('tipo_execucao', models.TextField(blank=True, null=True)),
                ('emergencial', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chamados',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField()),
                ('action', models.TextField(blank=True, null=True)),
                ('approved_budget_id', models.UUIDField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True, null=True)),
                ('review_details', models.TextField(blank=True, null=True)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('budget_id', models.UUIDField(blank=True, null=True)),
                ('approver_role', models.TextField(default='sindico')),
                ('decision', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_minerva', models.BooleanField(default=False)),
                ('minerva_justification', models.TextField(blank=True, null=True)),
                ('approval_type', models.TextField(default='ORCAMENTO')),
                ('approver_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('status', models.TextField(default='pendente')),
                ('description', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('alcada_nivel', models.IntegerField(default=1)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('work_order_id', models.UUIDField()),
                ('file_id', models.UUIDField()),
                ('hash_algorithm', models.TextField(default='SHA-256')),
                ('hash_hex', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by_user_id', models.UUIDField()),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'dossiers',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='ABERTA')),
                ('executor_type', models.TextField(blank=True, null=True)),
                ('executor_name', models.TextField(blank=True, null=True)),
                ('execution_notes', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(default='MEDIA')),
                ('is_emergency', models.BooleanField(default=False)),
                ('emergency_justification', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('provider_id', models.UUIDField(blank=True, null=True)),
                ('os_number', models.BigIntegerField(blank=True, null=True)),
                ('final_pdf_url', models.TextField(blank=True, null=True)),
                ('chamado_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'service_orders',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activity_type', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'service_order_activities',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('approved_by', models.UUIDField()),
                ('approver_role', models.TextField()),
                ('decision', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('response_status', models.TextField(default='PENDENTE')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('approval_type', models.TextField(default='ORCAMENTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'service_order_approvals',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fiscal_document_id', models.UUIDField()),
                ('document_kind', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'service_order_documents',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stock_item_id', models.UUIDField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'service_order_materials',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('photo_type', models.TextField()),
                ('file_url', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'service_order_photos',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('provider_name', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'service_order_quotes',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('vote', models.TextField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'service_order_votes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('opened_by_user_id', models.UUIDField()),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('category', models.TextField(default='ELETRICA')),
                ('priority', models.TextField(default='Media')),
                ('status', models.TextField(default='ABERTO')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField()),
                ('file_id', models.UUIDField()),
            ],
            options={
                'db_table': 'ticket_files',
                'unique_together': {('ticket_id', 'file_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_id', models.UUIDField()),
                ('created_by_user_id', models.UUIDField()),
                ('os_number', models.BigIntegerField()),
                ('os_type', models.TextField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('emergency_justification', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='CRIADA')),
                ('provider_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'work_orders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_id', models.UUIDField()),
                ('file_id', models.UUIDField()),
                ('phase', models.TextField()),
            ],
            options={
                'db_table': 'work_order_evidence',
                'unique_together': {('work_order_id', 'file_id')},
            },
        ),
    ]
