# Generated by Django 5.2.12 on 2026-03-30 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=50)),
                ('chave_storage', models.TextField()),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo_conteudo', models.CharField(max_length=100)),
                ('tamanho_bytes', models.BigIntegerField()),
                ('sha256_hex', models.CharField(blank=True, max_length=64, null=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'db_table': 'arquivos',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('provedor', models.CharField(default='ASAAS', max_length=20)),
                ('id_cliente_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('id_assinatura_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='endereco')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo_convite', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='codigo de convite')),
                ('convite_ativo', models.BooleanField(default=False, verbose_name='convite ativo')),
                ('status_assinatura', models.CharField(default='trial', max_length=20, verbose_name='status da assinatura')),
                ('assinatura_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da assinatura')),
                ('assinatura_expira_em', models.DateTimeField(blank=True, null=True, verbose_name='expiracao da assinatura')),
                ('pagarme_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID cliente Pagar.me')),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'db_table': 'condominios',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alcada_1_limite', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='limite alcada 1')),
                ('alcada_2_limite', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='limite alcada 2')),
                ('alcada_3_limite', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='limite alcada 3')),
                ('prazo_aprovacao_horas', models.IntegerField(default=48, verbose_name='prazo aprovacao (horas)')),
                ('notificar_moradores_acima', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='notificar moradores acima de')),
                ('limite_mensal_manutencao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_mensal_limpeza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_mensal_seguranca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orcamento_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alerta_orcamento_pct', models.IntegerField(default=70, verbose_name='alerta orcamento %')),
                ('orcamento_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Configuracao Financeira',
                'verbose_name_plural': 'Configuracoes Financeiras',
                'db_table': 'configuracoes_financeiras',
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(blank=True, null=True)),
                ('tipo_entidade', models.CharField(max_length=100)),
                ('entidade_id', models.UUIDField(blank=True, null=True)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'db_table': 'eventos_auditoria',
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acao', models.CharField(max_length=100)),
                ('entidade', models.CharField(blank=True, max_length=100, null=True)),
                ('entidade_id', models.UUIDField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'db_table': 'logs_atividade',
            },
        ),
        migrations.CreateModel(
            name='LogTransferenciaSindico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario_anterior_id', models.UUIDField()),
                ('usuario_novo_id', models.UUIDField()),
                ('alterado_por_id', models.UUIDField(blank=True, null=True)),
                ('papel_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('papel_novo', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario_anterior_desativado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Log Transferencia Sindico',
                'verbose_name_plural': 'Logs Transferencia Sindico',
                'db_table': 'logs_transferencia_sindico',
            },
        ),
        migrations.CreateModel(
            name='MembroCondominio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('SINDICO', 'Sindico'), ('SUB_SINDICO', 'Sub-Sindico'), ('CONSELHEIRO', 'Conselheiro Fiscal'), ('FUNCIONARIO', 'Funcionario'), ('MORADOR', 'Morador'), ('ADMIN', 'Administrador')], default='MORADOR', max_length=20, verbose_name='papel')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('inativo', 'Inativo'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='status')),
                ('padrao', models.BooleanField(default=False, verbose_name='condominio padrao')),
            ],
            options={
                'verbose_name': 'Membro do Condominio',
                'verbose_name_plural': 'Membros do Condominio',
                'db_table': 'membros_condominio',
            },
        ),
        migrations.CreateModel(
            name='PoliticaAprovacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_politica', models.CharField(max_length=50, verbose_name='tipo')),
                ('usar_limite_valor', models.BooleanField(default=False)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('requer_sindico', models.BooleanField(default=True)),
                ('requer_sub_sindico', models.BooleanField(default=False)),
                ('requer_conselho', models.BooleanField(default=False)),
                ('modo_decisao', models.CharField(default='MAIORIA', max_length=20)),
                ('sindico_desempate', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Politica de Aprovacao',
                'verbose_name_plural': 'Politicas de Aprovacao',
                'db_table': 'politicas_aprovacao',
            },
        ),
    ]
