# Generated by Django 5.2.12 on 2026-03-30 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='condominio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_financeira', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='eventoauditoria',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='logatividade',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_atividade', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='logatividade',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logtransferenciasindico',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_sindico', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='membrocondominio',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='membrocondominio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_condominio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='politicaaprovacao',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_aprovacao', to='condominios.condominio'),
        ),
        migrations.AlterUniqueTogether(
            name='membrocondominio',
            unique_together={('usuario', 'condominio')},
        ),
    ]
