# Generated by Django 5.2.12 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descricao')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'Categoria de Estoque',
                'verbose_name_plural': 'Categorias de Estoque',
                'db_table': 'categorias_estoque',
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('unidade_medida', models.CharField(default='UN', max_length=20, verbose_name='unidade')),
                ('quantidade_minima', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='qtd minima')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descricao')),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='estoque.categoriaestoque')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'db_table': 'itens_estoque',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_movimento', models.CharField(max_length=20, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=18)),
                ('custo_unitario_centavos', models.BigIntegerField(blank=True, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('movido_em', models.DateTimeField(auto_now_add=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem_servico_id', models.UUIDField(blank=True, null=True)),
                ('documento_fiscal_id', models.UUIDField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.itemestoque')),
                ('movido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentacao de Estoque',
                'verbose_name_plural': 'Movimentacoes de Estoque',
                'db_table': 'movimentacoes_estoque',
            },
        ),
    ]
