# Generated by Django 5.2.12 on 2026-03-30 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoChamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arquivo do Chamado',
                'verbose_name_plural': 'Arquivos do Chamado',
                'db_table': 'arquivos_chamado',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='titulo')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='categoria')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('CANCELADO', 'Cancelado'), ('PENDENTE_TRIAGEM', 'Pendente Triagem')], default='ABERTO', max_length=30, verbose_name='status')),
                ('emergencial', models.BooleanField(default=False, verbose_name='emergencial')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='motivo rejeicao')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='motivo cancelamento')),
                ('tipo_execucao', models.CharField(blank=True, max_length=50, null=True, verbose_name='tipo execucao')),
                ('motivo_fechamento', models.TextField(blank=True, null=True, verbose_name='motivo fechamento')),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'db_table': 'chamados',
            },
        ),
    ]
