# Generated by Django 5.2.12 on 2026-03-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0001_initial'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivochamado',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='condominios.arquivo'),
        ),
    ]
