# Generated by Django 5.2.12 on 2026-03-30 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0002_initial'),
        ('condominios', '0001_initial'),
        ('moradores', '0001_initial'),
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='aberto_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='moradores.unidade'),
        ),
        migrations.AddField(
            model_name='arquivochamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='chamados.chamado'),
        ),
        migrations.AlterUniqueTogether(
            name='arquivochamado',
            unique_together={('chamado', 'arquivo')},
        ),
    ]
