# Generated by Django 5.2.12 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(default='NF', max_length=20)),
                ('tipo_fonte', models.CharField(max_length=30, verbose_name='tipo fonte')),
                ('nome_emissor', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_emissor', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_tomador', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_tomador', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_verificacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('cidade_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_servico', models.CharField(blank=True, max_length=2, null=True)),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_impostos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('chave_acesso', models.TextField(blank=True, null=True)),
                ('url_arquivo', models.TextField(blank=True, null=True)),
                ('payload_original', models.JSONField(blank=True, null=True)),
                ('ordem_servico_id', models.UUIDField(blank=True, null=True)),
                ('status_aprovacao', models.CharField(default='pendente', max_length=20)),
                ('aprovado_por_subsindico_id', models.UUIDField(blank=True, null=True)),
                ('aprovado_por_subsindico_em', models.DateTimeField(blank=True, null=True)),
                ('voto_minerva_sindico', models.BooleanField(default=False)),
                ('voto_minerva_sindico_em', models.DateTimeField(blank=True, null=True)),
                ('nivel_alcada', models.IntegerField(default=1)),
                ('notificar_moradores', models.BooleanField(default=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_fiscais_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
                'db_table': 'documentos_fiscais',
            },
        ),
        migrations.CreateModel(
            name='AprovacaoDocFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel_aprovador', models.CharField(max_length=30)),
                ('decisao', models.CharField(blank=True, max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('votado_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('minerva', models.BooleanField(default=False)),
                ('justificativa_minerva', models.TextField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes_doc_fiscal', to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
                ('documento_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='fiscal.documentofiscal')),
            ],
            options={
                'verbose_name': 'Aprovacao Doc Fiscal',
                'verbose_name_plural': 'Aprovacoes Doc Fiscal',
                'db_table': 'aprovacoes_doc_fiscal',
            },
        ),
        migrations.CreateModel(
            name='ItemDocFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item_estoque_id', models.UUIDField(blank=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('documento_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.documentofiscal')),
            ],
            options={
                'verbose_name': 'Item Doc Fiscal',
                'verbose_name_plural': 'Itens Doc Fiscal',
                'db_table': 'itens_doc_fiscal',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_nota', models.CharField(max_length=30)),
                ('ordem_trabalho_id', models.UUIDField(blank=True, null=True)),
                ('fornecedor_id', models.UUIDField(blank=True, null=True)),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('chave_nota', models.CharField(blank=True, max_length=100, null=True)),
                ('emitido_em', models.DateField(blank=True, null=True)),
                ('valor_centavos', models.BigIntegerField(blank=True, null=True)),
                ('arquivo_id', models.UUIDField(blank=True, null=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'db_table': 'notas_fiscais',
            },
        ),
    ]
