# Generated by Django 5.2.12 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='codigo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descricao')),
                ('bloco', models.CharField(blank=True, max_length=20, null=True, verbose_name='bloco')),
                ('andar', models.CharField(blank=True, max_length=10, null=True, verbose_name='andar')),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidades',
                'unique_together': {('condominio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=255, verbose_name='nome completo')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/RG')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('bloco', models.CharField(blank=True, max_length=20, null=True, verbose_name='bloco')),
                ('unidade_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='unidade')),
                ('tipo_residencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='tipo de residencia')),
                ('torre', models.CharField(blank=True, max_length=20, null=True, verbose_name='torre')),
                ('numero_apartamento', models.CharField(blank=True, max_length=20, null=True, verbose_name='numero apartamento')),
                ('rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='rua')),
                ('numero_rua', models.CharField(blank=True, max_length=20, null=True, verbose_name='numero')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data nascimento')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='condominios.condominio')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moradores', to='moradores.unidade')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
                'db_table': 'moradores',
            },
        ),
        migrations.CreateModel(
            name='MoradorUnidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='moradores.unidade')),
            ],
            options={
                'verbose_name': 'Morador-Unidade',
                'verbose_name_plural': 'Moradores-Unidades',
                'db_table': 'morador_unidades',
                'unique_together': {('usuario', 'unidade')},
            },
        ),
    ]
