# Generated by Django 5.2.12 on 2026-03-28 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('legal_name', models.TextField()),
                ('trade_name', models.TextField(blank=True, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('has_restriction', models.BooleanField(default=False)),
                ('restriction_note', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('neighborhood', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('legal_nature', models.TextField(blank=True, null=True)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company_size', models.TextField(blank=True, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('main_activity', models.TextField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.TextField(blank=True, null=True)),
                ('tipo_servico', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='ativo')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cidade', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('contract_type', models.TextField(default='OUTROS')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='RASCUNHO')),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ProviderRiskAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('nivel_risco', models.TextField(blank=True, null=True)),
                ('situacao_receita', models.TextField(blank=True, null=True)),
                ('possui_protestos', models.BooleanField(default=False)),
                ('possui_processos', models.BooleanField(default=False)),
                ('noticias_negativas', models.BooleanField(default=False)),
                ('historico_interno', models.TextField(blank=True, null=True)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('relatorio_completo', models.TextField(blank=True, null=True)),
                ('consultado_em', models.DateTimeField(blank=True, null=True)),
                ('consultado_por', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(blank=True, db_column='condo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'db_table': 'provider_risk_analysis',
            },
        ),
    ]
