# Generated by Django 5.2.12 on 2026-03-28 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('document_type', models.TextField(default='NF')),
                ('source_type', models.TextField()),
                ('issuer_name', models.TextField(blank=True, null=True)),
                ('issuer_document', models.TextField(blank=True, null=True)),
                ('taker_name', models.TextField(blank=True, null=True)),
                ('taker_document', models.TextField(blank=True, null=True)),
                ('document_number', models.TextField(blank=True, null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('verification_code', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('service_city', models.TextField(blank=True, null=True)),
                ('service_state', models.TextField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.TextField(default='PENDENTE')),
                ('access_key', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('approval_status', models.TextField(default='pendente')),
                ('approved_by_subsindico', models.UUIDField(blank=True, null=True)),
                ('approved_by_subsindico_at', models.DateTimeField(blank=True, null=True)),
                ('sindico_voto_minerva', models.BooleanField(default=False)),
                ('sindico_voto_at', models.DateTimeField(blank=True, null=True)),
                ('alcada_nivel', models.IntegerField(default=1)),
                ('notify_residents', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'fiscal_documents',
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('approver_role', models.TextField()),
                ('decision', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_minerva', models.BooleanField(default=False)),
                ('minerva_justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_user', models.ForeignKey(db_column='approver_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('fiscal_document', models.ForeignKey(db_column='fiscal_document_id', on_delete=django.db.models.deletion.CASCADE, to='invoices.fiscaldocument')),
            ],
            options={
                'db_table': 'fiscal_document_approvals',
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stock_item_id', models.UUIDField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_document', models.ForeignKey(db_column='fiscal_document_id', on_delete=django.db.models.deletion.CASCADE, to='invoices.fiscaldocument')),
            ],
            options={
                'db_table': 'fiscal_document_items',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('invoice_type', models.TextField()),
                ('work_order_id', models.UUIDField(blank=True, null=True)),
                ('provider_id', models.UUIDField(blank=True, null=True)),
                ('invoice_number', models.TextField(blank=True, null=True)),
                ('invoice_key', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'stock_categories',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('unit', models.TextField(default='UN')),
                ('min_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.stockcategory')),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('move_type', models.TextField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost_cents', models.BigIntegerField(blank=True, null=True)),
                ('supplier_name', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('moved_by_user_id', models.UUIDField()),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.TextField(blank=True, null=True)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('fiscal_document_id', models.UUIDField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='invoices.stockitem')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
    ]
