# Generated by Django 5.2.12 on 2026-03-28 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('document', models.TextField(blank=True, null=True)),
                ('invite_code', models.TextField(blank=True, null=True)),
                ('invite_active', models.BooleanField(default=False)),
                ('subscription_status', models.TextField(default='trial')),
                ('subscription_id', models.TextField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pagarme_customer_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condos',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('entity_type', models.TextField()),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.TextField()),
                ('event_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'audit_events',
            },
        ),
        migrations.CreateModel(
            name='CondoApprovalPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('policy_type', models.TextField()),
                ('use_amount_limit', models.BooleanField(default=False)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('require_sindico', models.BooleanField(default=True)),
                ('require_sub_sindico', models.BooleanField(default=False)),
                ('require_conselho_fiscal', models.BooleanField(default=False)),
                ('decision_mode', models.TextField(default='MAIORIA')),
                ('syndic_tiebreaker', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'condo_approval_policies',
            },
        ),
        migrations.CreateModel(
            name='CondoFinancialConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('alcada_1_limite', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('alcada_2_limite', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('alcada_3_limite', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('approval_deadline_hours', models.IntegerField(default=48)),
                ('notify_residents_above', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('monthly_limit_manutencao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_limit_limpeza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_limit_seguranca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_budget_alert_pct', models.IntegerField(default=70)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo', models.OneToOneField(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'condo_financial_config',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('storage_key', models.TextField()),
                ('file_name', models.TextField()),
                ('content_type', models.TextField()),
                ('size_bytes', models.BigIntegerField()),
                ('sha256_hex', models.TextField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('full_name', models.TextField()),
                ('document', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('unit_label', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('residence_type', models.TextField(blank=True, null=True)),
                ('tower_block', models.TextField(blank=True, null=True)),
                ('apartment_number', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('street_number', models.TextField(blank=True, null=True)),
                ('complement', models.TextField(blank=True, null=True)),
                ('cpf_rg', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'residents',
            },
        ),
        migrations.CreateModel(
            name='SindicoTransferLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('old_user_id', models.UUIDField()),
                ('new_user_id', models.UUIDField()),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('old_role', models.TextField(blank=True, null=True)),
                ('new_role', models.TextField(blank=True, null=True)),
                ('old_user_deactivated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'sindico_transfer_logs',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('provider', models.TextField(default='ASAAS')),
                ('external_customer_id', models.TextField(blank=True, null=True)),
                ('external_subscription_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='ATIVO')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('full_name', models.TextField()),
                ('email', models.TextField()),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('cpf_rg', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile', models.TextField(default='MORADOR')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.TextField(blank=True, default='ativo', null=True)),
                ('residence_type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condo', models.ForeignKey(blank=True, db_column='condo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.condo')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('entity', models.TextField(blank=True, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='UserCondo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.TextField(default='MORADOR')),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.TextField(default='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'user_condos',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'user_units',
                'unique_together': {('user', 'unit')},
            },
        ),
    ]
